### ISSUE TITLE
Application settings listed as "okay" when incomplete; yields cascading failure upon save

### ISSUE THREAD

**Issue by ssamiei** [MD2Korg/mCerebrum-Study#13]
Application settings were listed as okay (a green checkmark) when not all settings were configured (e.g., phone sensor, AutoSense, MicrosoftBand). After tapping "Save" from the admin window, a cascading failure began and required force stop of the application and clearing of data from the database via the Android Application Manager.

**Comment by twhnat** [comment]
Should be resolved in the latest release.
