### ISSUE TITLE
MD2K Study app crashing

### ISSUE THREAD

**Issue by keitokawabata** [MD2Korg/mCerebrum-Study#15]
Version 0.3.2
kkrice2
Samsung S4, Phone 29

I went into MD2k study application to install all the applications to install all the apps. I changed my user id to kkrice 2. I changed the wake up and sleep time. I clicked save. 

I than received an infinite loop of 2 types of errors "Configuration file for Autosense doesn't exist. Please go to Menu-> settings" and "Phone sensor is not configured." 

I am unable to go to the settings menu because of the errors that keep coming out after I click ok.

**Comment by twhnat** [comment]
@keitokawabata This is a known issue that the next version of the Study app will address.  @ssamiei will reach out to you with a temporary solution.

**Comment by kevinmoran805** [comment]
I am experiencing the same infinite loop of errors which is preventing the usage of the Study app.

**Comment by twhnat** [comment]
@kevinmoran805 Are you running the latest version 0.3.3 of the Study application?  If not, please update all application and confirm that this issue still exists.

**Comment by kevinmoran805** [comment]
Running 0.3.2 but Airwatch has not pushed a newer version when I 'Sync' on
the phone.

**Comment by twhnat** [comment]
Should be resolved in the latest release.
