### ISSUE TITLE
mCerebrum crash after answering random survey

### ISSUE THREAD

**Issue by ssamiei** [MD2Korg/mCerebrum-Study#16]
mCerebrum, datakit, and notification manager all crashed shortly after responding to an EMA. After survey completion, I logged into the phone to end the day, and discovered all of the aforementioned apps had crashed. After re-opening mCerebrum, Datakit was not available, and the application crashed again. Re-opening brought me to a black screen. This required a force quit of mCerebrum before it would open again.

**Comment by monowar** [comment]
it should not crash in new version
