### ISSUE TITLE
Privacy countdown timer

### ISSUE THREAD

**Issue by bpahern** [MD2Korg/mCerebrum-Study#7]
This is non-critical, just a suggestion...
When Privacy mode is activated, it would be nice if the countdown timer could appear on the Privacy button on the home screen.

**Comment by twhnat** [comment]
@bpahern Is this completed and functioning based on the demo today?

**Comment by bpahern** [comment]
It is functioning, but note: the timer display is only updated in 5-6 second increments. I'm not sure if this is the final version of this enhancement, or if there is a plan to make it a true countdown (every second) in future updates. I will defer to you and @monowar

**Comment by twhnat** [comment]
@bpahern Is this fixed in the current version of the software?

**Comment by bpahern** [comment]
Yes
