### ISSUE TITLE
Study App Crashing

### ISSUE THREAD

**Issue by kevinmoran805** [MD2Korg/mCerebrum-Study#8]
In the process of setting up a Galaxy S4 for testing, I checked for updates to applications while in the Study app. All apps had an available update, so I elected to update the first application in the list (I can't recall which app it was now). After successfully updating, the phone was brought back to the Android home screen. I navigated to the Study app again and saw that it had a different icon. Upon attempting to open the Study app, the error message 'Unfortunately, Study has stopped.' appears and the app fails to launch.

Restarting phone does not fix this.

**Comment by twhnat** [comment]
Kevin, I believe that this is due to incorrect configuration files.  Please replace the mCerebrum folder in root directory with the one available in the `configurations` repository.

**Comment by kevinmoran805** [comment]
Thanks, Tim. This worked.

**Comment by twhnat** [comment]
Still a bug, default behavior needs to not crash when an invalid config
exists.

**Comment by twhnat** [comment]
Resolved in the latest study application
