### ISSUE TITLE
Micropayments

### ISSUE THREAD

**Issue by twhnat** [MD2Korg/mCerebrum-Study#9]
From conversation with Bonnie

Provide a way to show micropayments and totals as part of the study system after an EMA/EMI.

**Comment by kevinmoran805** [comment]
As per our call today (2/23/16), we’d like to display money earned after they complete each EMA. Also, at the end of the study I won’t be able to have access to some of the items that we’re incentivizing (responding to EMAs within 5min, completing 90% or more of EMAs, wearing sensors 70% of the targeted time, etc), so we’ll need to find a way to around that. 

Latest incentive structure here: 
https://drive.google.com/open?id=0B3Wenj2VFEIMZ181UnA1d2lnZFk

**Comment by twhnat** [comment]
https://www.pivotaltracker.com/story/show/113366303

**Comment by monowar** [comment]
implemented in new version
